
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'HREF SRC TAG_CLOSE TAG_OPEN TAG_SLASH_CLOSEdocument : elementselements : elements element\n                | elementelement : TAG_OPENelement : TAG_CLOSEelement : TAG_SLASH_CLOSEelement : HREFelement : SRC'
    
_lr_action_items = {'TAG_OPEN':([0,2,3,4,5,6,7,8,9,],[4,4,-3,-4,-5,-6,-7,-8,-2,]),'TAG_CLOSE':([0,2,3,4,5,6,7,8,9,],[5,5,-3,-4,-5,-6,-7,-8,-2,]),'TAG_SLASH_CLOSE':([0,2,3,4,5,6,7,8,9,],[6,6,-3,-4,-5,-6,-7,-8,-2,]),'HREF':([0,2,3,4,5,6,7,8,9,],[7,7,-3,-4,-5,-6,-7,-8,-2,]),'SRC':([0,2,3,4,5,6,7,8,9,],[8,8,-3,-4,-5,-6,-7,-8,-2,]),'$end':([1,2,3,4,5,6,7,8,9,],[0,-1,-3,-4,-5,-6,-7,-8,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'document':([0,],[1,]),'elements':([0,],[2,]),'element':([0,2,],[3,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> elements','document',1,'p_document','parser.py',14),
  ('elements -> elements element','elements',2,'p_elements','parser.py',21),
  ('elements -> element','elements',1,'p_elements','parser.py',22),
  ('element -> TAG_OPEN','element',1,'p_element_tag_open','parser.py',26),
  ('element -> TAG_CLOSE','element',1,'p_element_tag_close','parser.py',34),
  ('element -> TAG_SLASH_CLOSE','element',1,'p_element_tag_slash_close','parser.py',47),
  ('element -> HREF','element',1,'p_element_href','parser.py',52),
  ('element -> SRC','element',1,'p_element_src','parser.py',59),
]
