
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A_OPEN HREF IMG_OPEN SRC TAG_CLOSE TAG_SLASH_CLOSE URLdocument : element document\n                | element\n                | emptyelement : A_OPEN HREF URL TAG_CLOSEelement : IMG_OPEN SRC URL TAG_SLASH_CLOSEempty :'
    
_lr_action_items = {'A_OPEN':([0,2,11,12,],[4,4,-4,-5,]),'IMG_OPEN':([0,2,11,12,],[5,5,-4,-5,]),'$end':([0,1,2,3,6,11,12,],[-6,0,-2,-3,-1,-4,-5,]),'HREF':([4,],[7,]),'SRC':([5,],[8,]),'URL':([7,8,],[9,10,]),'TAG_CLOSE':([9,],[11,]),'TAG_SLASH_CLOSE':([10,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'document':([0,2,],[1,6,]),'element':([0,2,],[2,2,]),'empty':([0,2,],[3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> element document','document',2,'p_document','parser.py',9),
  ('document -> element','document',1,'p_document','parser.py',10),
  ('document -> empty','document',1,'p_document','parser.py',11),
  ('element -> A_OPEN HREF URL TAG_CLOSE','element',4,'p_element_a','parser.py',15),
  ('element -> IMG_OPEN SRC URL TAG_SLASH_CLOSE','element',4,'p_element_img','parser.py',19),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',23),
]
