
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'HREF SELF_CLOSING SRC TAG_CLOSE TAG_OPEN TEXThtml : elementoselementos : elemento elementos\n                 | elemento : TAG_OPENelemento : TAG_CLOSEelemento : SELF_CLOSING'
    
_lr_action_items = {'$end':([0,1,2,3,4,5,6,7,],[-3,0,-1,-3,-4,-5,-6,-2,]),'TAG_OPEN':([0,3,4,5,6,],[4,4,-4,-5,-6,]),'TAG_CLOSE':([0,3,4,5,6,],[5,5,-4,-5,-6,]),'SELF_CLOSING':([0,3,4,5,6,],[6,6,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'html':([0,],[1,]),'elementos':([0,3,],[2,7,]),'elemento':([0,3,],[3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> html","S'",1,None,None,None),
  ('html -> elementos','html',1,'p_html','parser.py',7),
  ('elementos -> elemento elementos','elementos',2,'p_elementos','parser.py',14),
  ('elementos -> <empty>','elementos',0,'p_elementos','parser.py',15),
  ('elemento -> TAG_OPEN','elemento',1,'p_elemento_tag_open','parser.py',19),
  ('elemento -> TAG_CLOSE','elemento',1,'p_elemento_tag_close','parser.py',24),
  ('elemento -> SELF_CLOSING','elemento',1,'p_elemento_self_closing','parser.py',32),
]
